### ISSUE TITLE
tput is not defined in Windows.

### ISSUE THREAD

**Issue by lanastasov** [MadRabbit/git-wayback-machine#5]
lib/git_wayback_machine/navigator.rb:44:in 'tput cols'

and 

lib/git_wayback_machine/history.rb:14:in 'tput cols'

**Comment by kaievns** [comment]
that is probably the case. but unfortunately i don't have a windows machine to fix it

**Comment by soumyaray** [comment]
not a windows user either here.  but @lanastasov, does it work if you [enable bash shell on windows 10](http://www.laptopmag.com/articles/use-bash-shell-windows-10)?
